development:
  adapter: async
  log_level: error

test:
  adapter: test

production:
  adapter: redis
  url: <%= Rails.application.credentials.redis_url || "redis://localhost:6379/1" %>
  channel_prefix: v2_ask_zafranudin_dev_production
